// Copyright (c) 2022 Lukin Aleksandr
#ifndef MAIN_CONFIGURATION_SETTINGS_H_
#define MAIN_CONFIGURATION_SETTINGS_H_

#pragma once

#define DEF_NUMBER_CONNECTION_ATTEMPTS_WIFI		100


#endif /* MAIN_CONFIGURATION_SETTINGS_H_ */
